test_giskard_network (test_giskard_network.TestGiskardNetwork) ... INFO:test_giskard_network:Starting node 0
Traceback (most recent call last):
  File "/usr/bin/poet-engine", line 11, in <module>
    load_entry_point('sawtooth-poet-engine==1.1.3', 'console_scripts', 'poet-engine')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/main.py", line 27, in <module>
    from sawtooth_poet_engine.engine import GiskardEngine
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/engine.py", line 25, in <module>
    from journal.block_wrapper import LAST_BLOCK_INDEX_IDENTIFIER
ModuleNotFoundError: No module named 'journal'
======== Running on http://127.0.0.1:8008 ========
(Press CTRL+C to quit)
writing file: /tmp/tmpjmucxwr6/keys/validator.priv
writing file: /tmp/tmpjmucxwr6/keys/validator.pub
Generated /tmp/tmpjmucxwr6/data/config-genesis.batch
Writing key state for PoET public key: 0262bf24...b734a334
Generating /tmp/tmpjmucxwr6/data/poet.batch
Processing /tmp/tmpjmucxwr6/data/config-genesis.batch...
Processing /tmp/tmpjmucxwr6/data/config.batch...
Processing /tmp/tmpjmucxwr6/data/poet.batch...
Generating /tmp/tmpjmucxwr6/data/genesis.batch
[2023-04-21 15:16:18.402 WARNING  (unknown file)] [src/pylogger.rs: 40] Started logger at level INFO
[2023-04-21 15:16:18.692 INFO     path] Skipping path loading from non-existent config file: /tmp/tmpjmucxwr6/etc/path.toml
[2023-04-21 15:16:18.694 INFO     validator] Skipping validator config loading from non-existent config file: /tmp/tmpjmucxwr6/etc/validator.toml
[2023-04-21 15:16:18.696 INFO     keys] Loading signing key: /tmp/tmpjmucxwr6/keys/validator.priv
[2023-04-21 15:16:18.713 INFO     cli] sawtooth-validator (Hyperledger Sawtooth) version 1.2.6
[2023-04-21 15:16:18.715 INFO     cli] config [path]: config_dir = "/tmp/tmpjmucxwr6/etc"; config [path]: key_dir = "/tmp/tmpjmucxwr6/keys"; config [path]: data_dir = "/tmp/tmpjmucxwr6/data"; config [path]: log_dir = "/tmp/tmpjmucxwr6/logs"; config [path]: policy_dir = "/tmp/tmpjmucxwr6/policy"
[2023-04-21 15:16:18.717 WARNING  cli] Network key pair is not configured, Network communications between validators will not be authenticated or encrypted.
[2023-04-21 15:16:18.723 INFO     state_verifier] Skipping state verification: chain head's state root is present
[2023-04-21 15:16:18.725 INFO     cli] Starting validator with parallel scheduler
[2023-04-21 15:16:18.737 INFO     interconnect] Listening on tcp://127.0.0.1:4004
[2023-04-21 15:16:18.741 INFO     genesis] Producing genesis block from /tmp/tmpjmucxwr6/data/genesis.batch
[2023-04-21 15:16:18.746 INFO     processor_manager] waiting for processor type sawtooth_settings: 1.0 to register
[2023-04-21 15:16:18.799 WARNING  processor_handlers] Max occupancy was not provided by transaction processor: 0615ca85dbadb3d269b37f0508973a14984711fe6fbb128f21d259c8f3945a248ae18b6f45be5f7789f1d1fb57cbc17e47ab1a5ca459a2625b07b7d4aedfdbd5. Using default max occupancy: 10
[2023-04-21 15:16:18.802 INFO     processor_handlers] registered transaction processor: connection_id=0615ca85dbadb3d269b37f0508973a14984711fe6fbb128f21d259c8f3945a248ae18b6f45be5f7789f1d1fb57cbc17e47ab1a5ca459a2625b07b7d4aedfdbd5, family=sawtooth_settings, version=1.0, namespaces=['000000'], max_occupancy=10
[2023-04-21 15:16:18.841 WARNING  processor_handlers] Max occupancy was not provided by transaction processor: 9e7daaaa499c61e294e0bfa80f19096c393e15e431db298d8a2be3d4e18d8f8e780eccd77ebdee1c95b7cec4854b72ab5a88eb56c5422a2966c5b417c6d3de14. Using default max occupancy: 10
[2023-04-21 15:16:18.851 INFO     processor_handlers] registered transaction processor: connection_id=9e7daaaa499c61e294e0bfa80f19096c393e15e431db298d8a2be3d4e18d8f8e780eccd77ebdee1c95b7cec4854b72ab5a88eb56c5422a2966c5b417c6d3de14, family=intkey, version=1.0, namespaces=['1cf126'], max_occupancy=10
[2023-04-21 15:16:18 INFO    core] [2023-04-21 15:16:18.853 WARNING  processor_handlers]register attempt: OK 
Max occupancy was not provided by transaction processor: abe7fc2a1b101e4d9da834541eb27994a83d7099ae7d79ca02411aaeadc6fc9e7175df2f205143fc02568e95b285a8486bd52c65dd510cc71e44b65e2fd070d0. Using default max occupancy: 10
[2023-04-21 15:16:18.864 INFO     processor_handlers] registered transaction processor: connection_id=abe7fc2a1b101e4d9da834541eb27994a83d7099ae7d79ca02411aaeadc6fc9e7175df2f205143fc02568e95b285a8486bd52c65dd510cc71e44b65e2fd070d0, family=sawtooth_validator_registry, version=1.0, namespaces=['6a4372'], max_occupancy=10
[2023-04-21 15:16:19 INFO    handler] Validator id 02e466edb56b5bd50070247801189ccc67aa770c497407af0a532c73424dcbb430 was added to the validator_map and set.
[2023-04-21 15:16:19.051 INFO     genesis] Genesis block created: e7aba9946680e44fd16e1466ce4af1c68cc44ba2f2293724507c1ee6fe4245397c9504a8c0178d706d47c36f8b280b588f6fb32d1e1a5e248deeeb50e0db9479 (block_num:0, state:bc7d7322e6fb6ebcc3f467507f70da4748695cc9d1a8b0fc5a7e5454c89636e5, previous_block_id:0000000000000000)
[2023-04-21 15:16:19.056 INFO     interconnect] Listening on tcp://127.0.0.1:5050
[2023-04-21 15:16:19.061 INFO     interconnect] Listening on tcp://127.0.0.1:8800
[2023-04-21 15:16:19.065 INFO     ffi] [src/journal/chain.rs: 946] Chain controller initialized with chain head: Block(id: e7aba9946680e44fd16e1466ce4af1c68cc44ba2f2293724507c1ee6fe4245397c9504a8c0178d706d47c36f8b280b588f6fb32d1e1a5e248deeeb50e0db9479, block_num: 0, state_root_hash: bc7d7322e6fb6ebcc3f467507f70da4748695cc9d1a8b0fc5a7e5454c89636e5, previous_block_id: 0000000000000000)
[2023-04-21 15:16:19.067 INFO     ffi] [src/journal/publisher.rs: 172] Now building on top of block, Block(id: e7aba9946680e44fd16e1466ce4af1c68cc44ba2f2293724507c1ee6fe4245397c9504a8c0178d706d47c36f8b280b588f6fb32d1e1a5e248deeeb50e0db9479, block_num: 0, state_root_hash: bc7d7322e6fb6ebcc3f467507f70da4748695cc9d1a8b0fc5a7e5454c89636e5, previous_block_id: 0000000000000000)
INFO:test_giskard_network:Starting node 1
Traceback (most recent call last):
  File "/usr/bin/poet-engine", line 11, in <module>
    load_entry_point('sawtooth-poet-engine==1.1.3', 'console_scripts', 'poet-engine')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/main.py", line 27, in <module>
    from sawtooth_poet_engine.engine import GiskardEngine
  File "/usr/lib/python3/dist-packages/sawtooth_poet_engine/engine.py", line 25, in <module>
    from journal.block_wrapper import LAST_BLOCK_INDEX_IDENTIFIER
ModuleNotFoundError: No module named 'journal'
======== Running on http://127.0.0.1:8009 ========
(Press CTRL+C to quit)
writing file: /tmp/tmp1cv64ogb/keys/validator.priv
writing file: /tmp/tmp1cv64ogb/keys/validator.pub
[2023-04-21 15:16:22.605 WARNING  (unknown file)] [src/pylogger.rs: 40] Started logger at level INFO
[2023-04-21 15:16:22.879 INFO     path] Skipping path loading from non-existent config file: /tmp/tmp1cv64ogb/etc/path.toml
[2023-04-21 15:16:22.881 INFO     validator] Skipping validator config loading from non-existent config file: /tmp/tmp1cv64ogb/etc/validator.toml
[2023-04-21 15:16:22.884 INFO     keys] Loading signing key: /tmp/tmp1cv64ogb/keys/validator.priv
[2023-04-21 15:16:22.898 INFO     cli] sawtooth-validator (Hyperledger Sawtooth) version 1.2.6
[2023-04-21 15:16:22.901 INFO     cli] config [path]: config_dir = "/tmp/tmp1cv64ogb/etc"; config [path]: key_dir = "/tmp/tmp1cv64ogb/keys"; config [path]: data_dir = "/tmp/tmp1cv64ogb/data"; config [path]: log_dir = "/tmp/tmp1cv64ogb/logs"; config [path]: policy_dir = "/tmp/tmp1cv64ogb/policy"
[2023-04-21 15:16:22.903 WARNING  cli] Network key pair is not configured, Network communications between validators will not be authenticated or encrypted.
[2023-04-21 15:16:22.911 INFO     state_verifier] Skipping state verification: chain head's state root is present
[2023-04-21 15:16:22.913 INFO     cli] Starting validator with serial scheduler
[2023-04-21 15:16:22.931 INFO     interconnect] Listening on tcp://127.0.0.1:4005
[2023-04-21 15:16:22.938 INFO     genesis] No chain head and not the genesis node: starting in peering mode
[2023-04-21 15:16:22.940 WARNING  processor_handlers] Max occupancy was not provided by transaction processor: 37ed653a88470b29258c6909ae5a55d01c7ac80316f8692023cb3dbb3c7d6bff48a0fd2b4f35075370b2d48a22735a31e3dbc631c5fc044b9a146cebb6058024. Using default max occupancy: 10
[2023-04-21 15:16:22.946 INFO     interconnect] Listening on tcp://127.0.0.1:5051
[2023-04-21 15:16:22.948 INFO     processor_handlers] registered transaction processor: connection_id=37ed653a88470b29258c6909ae5a55d01c7ac80316f8692023cb3dbb3c7d6bff48a0fd2b4f35075370b2d48a22735a31e3dbc631c5fc044b9a146cebb6058024, family=sawtooth_settings, version=1.0, namespaces=['000000'], max_occupancy=10
[2023-04-21 15:16:22.955 INFO     interconnect] Listening on tcp://127.0.0.1:8801
[2023-04-21 15:16:22.995 INFO     notifier] appending CONSENSUS_NOTIFY_ENGINE_ACTIVATED
[2023-04-21 15:16:22.998 INFO     notifier] appending CONSENSUS_NOTIFY_ENGINE_ACTIVATED
[2023-04-21 15:16:23 INFO    core][2023-04-21 15:16:23.032 WARNING  processor_handlers]  register attempt: OKMax occupancy was not provided by transaction processor: f30444cf853126ed103c2818b8ff8e267c91ac0c784b4148fc3af2f56a340b5bd9b8044fd03598eb6ef81abf5ce8da2bd3d35366fec06cd75f2303a3b0411e26. Using default max occupancy: 10

[2023-04-21 15:16:23.036 INFO     processor_handlers] registered transaction processor: connection_id=f30444cf853126ed103c2818b8ff8e267c91ac0c784b4148fc3af2f56a340b5bd9b8044fd03598eb6ef81abf5ce8da2bd3d35366fec06cd75f2303a3b0411e26, family=sawtooth_validator_registry, version=1.0, namespaces=['6a4372'], max_occupancy=10
[2023-04-21 15:16:23.081 WARNING  processor_handlers] Max occupancy was not provided by transaction processor: 036d5033945c008d71a7b17fc84a80158c53de271adedc6e816e96e6e449c8d8e957b456138f184f5bb3b10e46ecb8d343dbed96240328a7248525583f25599e. Using default max occupancy: 10
[2023-04-21 15:16:23.084 INFO     processor_handlers] registered transaction processor: connection_id=036d5033945c008d71a7b17fc84a80158c53de271adedc6e816e96e6e449c8d8e957b456138f184f5bb3b10e46ecb8d343dbed96240328a7248525583f25599e, family=intkey, version=1.0, namespaces=['1cf126'], max_occupancy=10
[2023-04-21 15:16:23 INFO    handler] Validator id 02e466edb56b5bd50070247801189ccc67aa770c497407af0a532c73424dcbb430 was added to the validator_map and set.
[2023-04-21 15:16:23.290 INFO     (unknown file)] [src/journal/publisher.rs: 172] Now building on top of block, Block(id: e7aba9946680e44fd16e1466ce4af1c68cc44ba2f2293724507c1ee6fe4245397c9504a8c0178d706d47c36f8b280b588f6fb32d1e1a5e248deeeb50e0db9479, block_num: 0, state_root_hash: bc7d7322e6fb6ebcc3f467507f70da4748695cc9d1a8b0fc5a7e5454c89636e5, previous_block_id: 0000000000000000)
INFO:test_giskard_network:

started nodes


INFO:test_giskard_network:Sending populate txns
INFO:test_giskard_network:

populated batches


ERROR

======================================================================
ERROR: test_giskard_network (test_giskard_network.TestGiskardNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/test_giskard_network.py", line 57, in test_giskard_network
    'ztest_minimum_win_count': 3,
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/test_giskard_network.py", line 111, in _run_giskard_network_test
    LOGGER.info(GiskardTester.create_GState_from_file().__str__())
  File "/usr/lib/python3/dist-packages/sawtooth_poet_tests/giskard_tester.py", line 97, in create_GState_from_file
    nstates = jsonpickle.decode(content)
  File "/home/lnsandn/.local/lib/python3.6/site-packages/jsonpickle/unpickler.py", line 84, in decode
    data = backend.decode(string)
  File "/home/lnsandn/.local/lib/python3.6/site-packages/jsonpickle/backend.py", line 72, in decode
    raise e
  File "/home/lnsandn/.local/lib/python3.6/site-packages/jsonpickle/backend.py", line 69, in decode
    return self.backend_decode(name, string)
  File "/home/lnsandn/.local/lib/python3.6/site-packages/jsonpickle/backend.py", line 225, in backend_decode
    return self._decoders[name](string, *optargs, **decoder_kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 9.446s

FAILED (errors=1)
init tester
tester bound sockets
